### ISSUE TITLE
On the fly changes are not detected

### ISSUE THREAD

**Issue by markiewb** [Chris2011/readmeinprojectview#1]
See implementation at https://github.com/nigjo/NBRelaseFilesView/tree/master/src/de/nigjo/nb/releaseview

**Comment by markiewb** [comment]
Or https://netbeans.org/bugzilla/show_bug.cgi?id=248175

**Comment by Chris2011** [comment]
What does that mean? Creating a README file or whatever the pattern matches, doesn't show it immediately?

**Comment by Chris2011** [comment]
1.5.0 is released.

**Comment by Chris2011** [comment]
Thx for contribution :)
