### ISSUE TITLE
What about LICENSE file?

### ISSUE THREAD

**Issue by taringamberini** [Chris2011/readmeinprojectview#10]
This plugin solved the "README file part" of the bug https://netbeans.org/bugzilla/show_bug.cgi?id=258726

It would be possible having the LICENSE file in the Project view too?

Thank you very much for this plugin,
Tarin

**Comment by markiewb** [comment]
Please provide a pull-request!

**Comment by cassman42** [comment]
I've raised a PR to add the LICENSE file

**Comment by markiewb** [comment]
@cassman42 Thank you. The new owner of the project @Chris2011 can/will take over.

**Comment by Chris2011** [comment]
Fixed in 1.4.0. Thx for the pr @cassman42.
