### ISSUE TITLE
added "Jenkinsfile" to configuration but does not show up

### ISSUE THREAD

**Issue by wumpz** [Chris2011/readmeinprojectview#14]

**Comment by wumpz** [comment]
all other preconfigured names work at least for the project types I use (e.g. maven)

**Comment by wumpz** [comment]
by the way I am using versio 1.5.0 with Netbeans 11.0

**Comment by Chris2011** [comment]
Try out "jenkinsfile" and it should work. Problem could be that the text inside must be lower case. Will fix this later but for now "jenkinsfile" should work as expected.

**Comment by wumpz** [comment]
@Chris2011 This did it. +1
