### ISSUE TITLE
Exact names are not possible.

### ISSUE THREAD

**Issue by Chris2011** [Chris2011/readmeinprojectview#16]
When I add "Jenkinsfile" to the list, the Jenkinsfile will not appear. If I add "jenkinsfile" the Jenkinsfile appears in the Projects list. So IMHO it should be possible to write whatever you want and make the check toLowerCase in any case.

Options         => Result
"JeNKinsFile" => JenkinsFile
"readme"       => README.md

**Comment by Chris2011** [comment]
I would like to give this task to you too @skyghis if you would like to check/change it, If not I can have a look later.

**Comment by skyghis** [comment]
It's a bug, The comparison should be case insensitive from what I had seen.

Assign me the task I will take a look this week.

**Comment by Chris2011** [comment]
great, thx :)

**Comment by Chris2011** [comment]
If you do a PR, can you try to make a PR against master? It should not possible. Just FYI. Would like to test it :)

**Comment by skyghis** [comment]
![image](https://user-images.githubusercontent.com/1068552/60294760-655c5b00-9922-11e9-8132-aa85ed6daf47.png)

I confirm PR on master is not allowed.

**Comment by Chris2011** [comment]
Na, it only means, that a review is required but you still created a PR against master which is still possible and not blocked. Thx for testing :)
