### ISSUE TITLE
COMPILATION ERROR

### ISSUE THREAD

**Issue by Vitexus** [Chris2011/readmeinprojectview#21]
COMPILATION ERROR : 
-------------------------------------------------------------
/home/vitex/Projects/NetBeans/readmeinprojectview/target/generated-sources/annotations/de/markiewb/netbeans/plugins/readmeinprojectview/Bundle.java:[3,17] error: package javax.annotation does not exist

The Java 8 use this:
```java
@javax.annotation.Generated(value="org.netbeans.modules.openide.util.NbBundleProcessor")
```

But Java 9 use "processing"

```java
@javax.annotation.processing.Generated(value="org.netbeans.modules.openide.util.NbBundleProcessor")
```

I do not know where/how to change. 
Please help.

**Comment by Chris2011** [comment]
Hey, you need to change the version to build the plugin from Java 9 to Java 1.8 in the properties of the plugin. I don't know atm how to fix this for Java 9, but this is first not a bug and second happens in every plugin of NetBeans where we use the annotations. At the end, it is very simple, but if you don't need java 9 specific stuff, just use JDK 1.8 or have a look into other NetBeans plugins how to handle it and if you find the solution, please just le me know :)
