### ISSUE TITLE
Doesn't seem to work with NB 15

### ISSUE THREAD

**Issue by fillumina** [Chris2011/readmeinprojectview#23]
Unfortunately it doesn't work with NB 15.
That's a pity, the plugin was really useful, hope you'll find the time to update it.
Thanks

**Comment by Chris2011** [comment]
Can you please be more specific, what is not working? How can I reproduce it? Is installation not working? The functionality after installation? Are there any errors? Etc. Need also Info of your environment, JDK, operating system etc.

**Comment by fillumina** [comment]
Thanks for your quick answer!
None of the specified files is shown in the 'Project Files' node of the 'Projects' panel.

This is the plugin version as specified in the plugin conf of NB:
`Version: 1.6.0 Source: 1562333398_readmeinprojectview-1.6.0.nbm`

I am running Ubuntu 22.04.
Java is configured by sdkman (not standard ubuntu way).

```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

```
System Info: 
  Product Version         = Apache NetBeans IDE 15
  Operating System        = Linux version 5.15.0-52-generic running on amd64
  Java; VM; Vendor        = 17.0.2; OpenJDK 64-Bit Server VM 17.0.2+8; Eclipse Adoptium
  Runtime                 = OpenJDK Runtime Environment 17.0.2+8
  Java Home               = /home/fra/.sdkman/candidates/java/17.0.2-tem
  System Locale; Encoding = en_US (nb); UTF-8
```

In the plugin options I have the following:
```
./.gitlab-ci.yml
./readme
./authors
./changelog
./dockerfile
./docker-compose.yml
./docker-compose.yaml
./contributing
./license
./.yo-rc.json
./README.md
./README.markdown
./angular.json
./package.json
./tsconfig.json
./tsconfig.app.json
./tsconfig.spec.json
```

**Comment by fillumina** [comment]
I forgot to mention that no error is present in the IDE log.

**Comment by Chris2011** [comment]
Thx, I will check it as soon as I can. Unfortunately I don't have ubuntu but maybe it is also on Windows.

**Comment by nmatt** [comment]
@Chris2011: FYI it works for me on Windows 10 with NetBeans 15.

**Comment by Chris2011** [comment]
hey @nmatt thx for the info :)

**Comment by nmatt** [comment]
@Chris2011: It only works with specifying the basename though. I.e. to show "logging.properties", "logging" must be configured; configuring "logging.properties" doesn't work. Similarly, specifying paths doesn't work,

**Comment by fillumina** [comment]
> @Chris2011: It only works with specifying the basename though. I.e. to show "logging.properties", "logging" must be configured; configuring "logging.properties" doesn't work. Similarly, specifying paths doesn't work,

That's it! I just removed the extensions and the path references and it works.

from:
```
./REAMDE.md
./README.txt
./readme.txt
```

to just:
```
readme
```

Thanks Chris2011!!

**Comment by fillumina** [comment]
I meant thanks nmatt!! (sorry I got confused)
