### ISSUE TITLE
Plugin only 'comes alive' after Reset Windows selected in the Windows menu

### ISSUE THREAD

**Issue by BobFutrelle** [Chris2011/readmeinprojectview#4]
Other folks may have different mileage.
But I had to discover that on my own.

Now it works just fine.

**Comment by Chris2011** [comment]
Hey @BobFutrelle can you please be more specific and give more steps to reproduce. Thx.

**Comment by Chris2011** [comment]
When I understand it right, it should be fixed by #13 in version 1.5.0. But because of missing information I will close it after I release the new version and if this still happens, please create a new ticket with steps to reproduce thx.

**Comment by Chris2011** [comment]
Please test 1.5.0
