### ISSUE TITLE
Add an option panel to choose files name/pattern to display

### ISSUE THREAD

**Issue by skyghis** [Chris2011/readmeinprojectview#8]
Instead of hard coded list of files, why not provide an option panel where the user can configure it?

BTW, Thanks for this very useful plug-in !

**Comment by Chris2011** [comment]
Hey @skyghis if you like and still using the plugin, would you be so kind and create a PR for this? That would be great :)

**Comment by skyghis** [comment]
I have zero knowledge about Netbeans plugin development.
Do you have a documentation or a sample code to create an option panel for the plugin ?

**Comment by Chris2011** [comment]
Sure, here it is: https://platform.netbeans.org/tutorials/nbm-options.html I would say I think it makes sense to have it under Misc and not a new top level option panel.

**Comment by Chris2011** [comment]
I will update it to NetBeans 10, hope this is ok for you too.

**Comment by skyghis** [comment]
No problem, I use Netbeans 11.

**Comment by Chris2011** [comment]
And we are online. Thx.
